# Generated by Django 2.0.3 on 2020-01-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20191029_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='isWritter',
            field=models.BooleanField(default=False),
        ),
    ]
