# Generated by Django 2.0.3 on 2020-01-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_auto_20200119_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profileImage',
            field=models.CharField(default='https://res.cloudinary.com/dgknrkenk/image/upload/v1579667093/gzhbok57go27agvxmwvv.jpg', max_length=1000),
        ),
    ]
