# Generated by Django 2.0.3 on 2020-01-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_useraccount_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='profileImage',
            field=models.CharField(default='https://res.cloudinary.com/dgknrkenk/image/upload/v1579667401/uwjxuqzu4baspaqybrmp.png', max_length=1000),
        ),
    ]
