# Generated by Django 2.0.3 on 2019-10-30 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
