# Generated by Django 2.0.3 on 2019-11-25 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0004_auto_20191124_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('content', models.CharField(max_length=500)),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mention_user', to=settings.AUTH_USER_MODEL)),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_comment', to='Post.Comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
