# Generated by Django 2.0.3 on 2019-11-28 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_remove_reaction_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='Post.Post'),
        ),
    ]
