# Generated by Django 2.0.3 on 2019-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_reaction_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
