# Generated by Django 2.0.3 on 2019-11-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_auto_20191128_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='time',
        ),
    ]
