# Generated by Django 2.0.3 on 2019-11-28 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_remove_reaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reaction',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 28, 1, 49, 15, 645256)),
        ),
    ]
