# Generated by Django 2.0.3 on 2020-01-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0006_auto_20191230_2212'),
        ('Post', '0014_auto_20191226_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogArticle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_article', to='BlogPost.BlogArticle'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='Post.Post'),
        ),
    ]
