# Generated by Django 2.0.3 on 2020-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20200107_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='blogArticle',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='article',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='parentComment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
