# Generated by Django 2.0.3 on 2019-12-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_remove_blogarticle_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='isPublished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='titleImageLink',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='blogarticle',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
