# Generated by Django 2.0.3 on 2019-12-27 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_auto_20191226_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogarticle',
            name='content',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='body',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='blogArticles',
            field=models.ManyToManyField(related_name='blog_post', to='BlogPost.BlogArticle'),
        ),
    ]
