# Generated by Django 2.0.3 on 2019-12-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0004_auto_20191227_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='blurb',
            field=models.CharField(default='', max_length=200),
        ),
    ]
