# Generated by Django 2.0.3 on 2020-01-09 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogArticle',
            new_name='article',
        ),
    ]
