# Generated by Django 2.0.3 on 2020-01-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0017_auto_20200109_1320'),
        ('Comment', '0002_auto_20200109_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_post', to='Post.Post'),
        ),
    ]
