# Generated by Django 2.0.3 on 2020-01-18 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0006_auto_20191230_2212'),
        ('Comment', '0003_reply_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_article', to='BlogPost.BlogArticle'),
        ),
    ]
